GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ka",
    "number": "123456789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "0176 2018 34 40"
}

###

PUT http://localhost:3001/api/persons/60132fb8f8c7c927348041f1
Content-Type: application/json

{
    "name": "Kaan",
    "number": "123456789"
}
